

apiVersion: v1
kind: Service
metadata:
  name: eventbridge
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    pavedroad.service: eventbridge
  type: NodePort
status:
  loadBalancer: {}
