
resources:
  - eventbridge-deployment.yaml
  - eventbridge-service.yaml

commonLabels:
  pavedroad.service: eventbridge

commonAnnotations:
  pavedroad.roadctl.version: v1.0.0beta
  pavedroad.roadctl.web: www.pavedroad.io
  pavedroad.roadctl.support: support@pavedroad.io

configMapGenerator:
- name: eventbridge-configmap
  literals:
  - database-ip=staging-db
  - ip=0.0.0.0
  - port=8083
  - host-ip=staging-db.pavedroad

