
resources:
  - eventbridge-deployment-stag-aws.yaml
  - eventbridge-service-stag-aws.yaml

commonLabels:
  pavedroad.service: eventbridge
  pavedroad.env: stag

commonAnnotations:
  pavedroad.roadctl.version: alphav1
  pavedroad.roadctl.web: www.pavedroad.io
  pavedroad.roadctl.support: support@pavedroad.io

configMapGenerator:
- name: eventbridge-configmap
  literals:
  - ip=0.0.0.0
  - port=8081
  - prlog-auto-init=true
  - prlog-conf-type=env
  - prlog-enable-kafka=true
  - prlog-file-format=text
  - prlog-file-location=logs/eventbridge.log"
  - prlog-kafka-brokers=kafka:9092

