
apiVersion: v1
kind: Secret
metadata:
  name: microk8s-secret
  lables:
    - CustomerID:1234
    - UserID:5678
    - AuthorizationToken:none
    - ReferenceID:none
type: Opaque
data:
  accesskey: test1
  secretkey: test2
