
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: eventbridge
  labels:
    CustomerID: "1234"
    UserID: "5678"
    AuthorizationToken: "none"
    ReferenceID: "none"
spec:
  service:
    ports:
      - port: 12001
        targetPort: 12001
  webhook:
    eventbridge:
      port: "12001"
      endpoint: eventbridge
      method: POST
