loadFrom: network
environmentName: production
eventBridgeConfigURL: https://api.pavedroad.io/api/v1/namespace/pavedroad/customers
eventBridgePlogsURL: https://api.pavedroad.io/api/v1/namespace/pavedroad/plogs
eventBridgePostHost: eventbridge
configFile: customers.yaml
k8sService: -eventsource-svc.argo-events
