
apiVersion: skaffold/v2beta10
kind: Config
build:
  insecureRegistries:
    - localhost:32000
  tagPolicy:
    sha256: {}
  artifacts:
  - image: localhost:32000/pavedroad-io/eventbridge
    context: .
    custom:
      dependencies:
        paths:
          - "**.go"
deploy:
  kustomize:
    paths:
    - "manifests/kubernetes/dev"
profiles:
  - name: dev-debug
    activation:
    - env: GODEBUG=true
    deploy:
      kustomize:
        paths:
        - "manifests/kubernetes/dev-debug"
  - name: staging
    build:
      artifacts:
      - image: 400276217548.dkr.ecr.us-west-1.amazonaws.com/io.pavedroad.stagging/eventbridge
        context: .
        docker:
          dockerfile: manifests/Dockerfile
    deploy:
      kustomize:
        paths:
        - "manifests/kubernetes/stag"
