
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pavedroad

bases:
  - eventbridge
  - ingress

commonLabels:
  pavedroad.env: staging

commonAnnotations:
  pavedroad.kustomize.base: eventbridge/manifests/kubernetes/stag
  pavedroad.kustomize.bases: "eventbridge"
